project:
  type: website
  output-dir: docs

website:
  title: "Minicurso de Risco de Crédito"
  navbar: false
  sidebar: false
  page-navigation: false

format:
  revealjs:
    theme: default
    css: estilos-dark.css
    slide-number: true
    width: 1600
    height: 900
    margin: 0.02
    center: false
    transition: fade